Bugfixes
src/hooks/mounted.ts(2,33): error TS2304: Cannot find name 'useState'.
src/hooks/mounted.ts(4,3): error TS2304: Cannot find name 'useEffect'.
src/worker/static-assets/index.ts(7,1): error TS2578: Unused '@ts-expect-error' directive.