Fix TS errors when upgrading to react 19
Fix
Error: src/components/Tooltip/index.tsx(41,9): error TS2353: Object literal may only specify known properties, and ''data-state'' does not exist in type 'HTMLProps<Element>'.
Error: src/pages/index/components/MonitorPanel/index.tsx(234,25): error TS2322: Type '{ children: Element; as: string; className: string; style: { width: string; }; }' is not assignable to type 'IntrinsicAttributes & HTMLAttributes<HTMLElement> & { asChild?: boolean | undefined; } & RefAttributes<HTMLElement>'.

Fix error TS2698

error TS2698: Spread types may only be created from object types.

Fix error TS2698

Error: src/components/Tooltip/index.tsx(40,9): error TS2698: Spread types may only be created from object types.

Fix error TS2353

Fix Error: src/components/Tooltip/index.tsx(41,9): error TS2353: Object literal may only specify known properties, and ''data-state'' does not exist in type 'HTMLProps<Element>'.